### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Gouvernathor** [Gouvernathor/Ecclesia#1]
- Convert to a full module
  - [x] take example on parliamentarch for the files layout
  - [x] establish a minimal python version
  - [ ] publish on pypi (under the name Ecclesia)
- [ ] Add a tests suite and trigger them using an action
- [ ] Document the API, probably in a Wiki but include a general plan in the readme
- [ ] Use the better NamedTuple in elections.\_\_init\_\_
- [ ] ~~Make the results_format module iterable, using class substitution~~
- [ ] Annotate the slots attributes
- [ ] Add \_\_all\_\_ in every module (except private modules like _settings)
- [ ] Take out the slots with preference to annotations ?
- [ ] Reform the contingency attribute of Attribution classes
  - maybe have an abstract class with `contingency: Attribution[...]` (and threshold ? not for condorcet...) and have classes that take a contingency have it as second base class ?
- [ ] Replace the taken_format class attribute with a generic annotation ? Will make things way simpler, at the cost of making it not observable at runtime.
- The Vote class
  - [ ] add the blank votes as a third element
  - [ ] convert to new-style NamedTuple
  - [ ] think of reestablishing ordering methods rather than the order static method
